export const chatList = {
    assetDetail: {
        userId: "",
        _id: "",
        title: "",
        description: "",
        imageUrl: "",
        price: 0,
        sold: false,
        statusCode: 4,
        statusText: "",
        title: "",
        units: { symbol: "₹", currency_code: "INR" },
    },
    assetId: "",
    chatId: "",
    deliveredAt: "",
    exchangeAssetId: "",
    groupChat: "",
    initiated: false,
    isExchange: false,
    messageId: "",
    messageType: 1,
    offerReplyStatus: null,
    payload: "",
    phoneNumber: "",
    profilePic: "",
    receiverId: "",
    recipientId: "",
    senderId: "",
    status: 3,
    totalUnread: 0,
    userName: "",
};