import { palette } from "./palette";

const customTheme = {
  light: {
    type: "light",
    palette: palette,
    appColor: palette.l_base,
    aboutPageBg: palette.l_aboutpage_bg,
    aboutPageLabelColor: palette.l_aboutpage_label,
    drawerBackground: palette.l_drawer_bg,
    primary: palette.l_base,
    text: palette.l_app_text,
    iconColor: '#5F596B',
    text_light_grey: palette.d_light_grey,
    background: palette.l_app_bg,
    background2: palette.l_background,
    border: palette.l_input_bg,
    shoutoutDialogBg: palette.l_input_bg,
    sectionBackground: palette.l_section_bg,
    markatePlaceLabelColor: palette.l_category_label,
    markatePlaceBackground: palette.l_markatplace_bg,
    footerTextColor: "#000",
    footerBgColor: "#fff",
    shoutoutField: palette.l_shoutout_fieldBg,
    shoutout_mobile_sell: palette.l_shoutout_sell,
    shoutout_success: palette.l_success,
    markatePlaceHoverColor: palette.l_markateplace_label_hover,
    priceSliderBg: palette.l_slider_bg,
    priceSliderPointBg: palette.l_slider_point,
    dialogSectionBg: "var(--l_sidebar_bg)",
    chatMsgBg: "var(--l_sidebar_bg)",
    theme: "#F1F1F1",
    labelbg: "#f1f1f1",
    exclusive_post_bg: "black", // hex color code does not work
    postCard: {},
    iconColor: palette.l_white,
    perticularShoutoutSectionBg: palette.l_perticular_shoutout_sectionBg,
    otherprofileInactiveTabColor: palette.l_otherprofile_inactiveTab,
    gradientBgClr: "linear-gradient(96.81deg, #D33AFF 0%, #FF71A4 100%)",
    leftIcon: {
      position: "absolute",
      top: "50%",
      left: "0",
      cursor: "pointer",
      transform: "translateY(-50%)",
    },
    rightIcon: {
      position: "absolute",
      top: "25px",
      right: "20px",
      cursor: "pointer",
      transform: "translateY(-50%)",
    },
    loginBg: {
    },
    signupBg: {
    },
    forgetPassBg: {
    },
    documentBg: {
    },
    button: {
      text: palette.l_app_text,
      background: palette.l_light_grey,
      fontFamily: `"Roboto", "sans-serif"`,
      fontSize: "15px",
      fontWeight: "normal",
      padding: "10px 15px",
      border: "none",
      margin: "10px 0",
    },
    blueButton: {
      text: palette.white,
      background: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: "none",
    },
    bulkButton: {
      text: palette.white,
      background: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "6px 15px",
      margin: "0",
      border: "none",
    },
    blueSlotButton: {
      text: palette.white,
      background: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "12px",
      fontWeight: "600",
      padding: "4px 15px",
      margin: "0",
      height: 'fit-content',
      border: "none",
    },
    global__btn: {
      background: palette.white,
      color: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: "none",
    },
    dv_blueButton: {
      background: palette.l_base,
      text: palette.white,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "1.171vw",
      fontWeight: "600",
      padding: "10px 6px",
      border: "none",
      margin: "0",
    },
    blueBorderButton: {
      text: palette.l_base,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.l_base}`,
    },
    redBorderButton: {
      text: palette.l_red,
      background: palette.transparent,
      hoverBackground: palette.l_red,
      hoverText: palette.white,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "5px 15px",
      margin: "0",
      border: `1px solid ${palette.l_red}`,
    },
    redButton: {
      text: palette.white,
      background: palette.l_red,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
    },
    dv_blueBorderButton: {
      text: palette.l_base,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "1.171vw",
      fontWeight: "600",
      padding: "8px 6px",
      margin: "0",
      border: `1px solid ${palette.l_base}`,
    },
    whiteButton: {
      text: palette.white,
      background: palette.l_app_bg,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0 auto",
      border: "none",
      position: "relative",
    },
    whiteBorderButton: {
      text: palette.white,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.white}`,
    },
    greyBorderButton: {
      background: palette.transparent,
      text: palette.l_light_grey,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      border: `1px solid ${palette.l_light_grey}`,
    },
    header: {
      position: "sticky",
      left: "0",
      top: "0",
      zIndex: "101",
      width: "100%",
      background: palette.l_profileCard_bgColor,
      borderBottom: `1px solid ${palette.l_border}`,
      zIndex: 99,
    },
    inputBox: {
      padding: "0 0 0 15px",
      background: palette.l_section_bg,
      border: "1px solid var(--l_base)",
      borderRadius: "20px",
      height: "44px",
      fontSize: "16px",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.l_app_text,
    },
    search_input: {
      padding: "0 0 0 50px",
      background: palette.d_input_bg,
      border: "none",
      borderRadius: "20px",
      height: "44px",
      fontSize: "16px",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.l_app_text,
    },
    dv_search_input: {
      width: "18.594vw",
      padding: "0 0 0 2.562vw",
      background: palette.l_input_bg,
      border: "none",
      borderRadius: "1.611vw",
      height: "2.928vw",
      fontSize: "1.098vw",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.l_app_text,
    },
    dv_markatePlace_input: {
      width: "100%",
      padding: "0 0 0 2.562vw",
      background: palette.l_input_bg,
      border: "none",
      borderRadius: "1.611vw",
      height: "2.928vw",
      fontSize: "1.098vw",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.l_app_text,
    },
    searchIcon: {
      position: "absolute",
      top: "50%",
      left: "20px",
      zIndex: "9",
      transform: "translateY(-50%)",
    },
    borderBtm: {
      borderBottom: `1px solid ${palette.l_border}`,
    },
    blueColorFieldButton: {
      text: palette.d_app_text,
      background: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.l_base}`,
    },
  },
  dark: {
    type: "dark",
    palette: palette,
    appColor: palette.d_base,
    drawerBackground: palette.d_drawer_bg,
    footerTextColor: "#c0c0c0",
    aboutPageBg: palette.d_aboutpage_bg,
    aboutPageLabelColor: palette.d_aboutpage_label,
    footerBgColor: "#1C1C1C",
    primary: palette.d_base,
    shoutoutDialogBg: palette.l_input_bg,
    text: palette.d_app_text,
    iconColor: '#5F596B',
    background: palette.d_app_bg,
    background2: palette.d_background,
    shoutoutField: palette.d_shoutout_fieldBg,
    shoutout_mobile_sell: palette.d_shoutout_sell,
    shoutout_success: palette.d_success,
    markatePlaceBackground: palette.d_markatplace_bg,
    markatePlaceHoverColor: palette.d_markateplace_label_hover,
    markatePlaceLabelColor: palette.d_category_label,
    border: palette.d_input_bg,
    dialogSectionBg: "#F5D0FF0D",
    chatMsgBg: "var(--l_app_bg)",
    theme: "#F1F1F1",
    labelbg: "#323448",
    exclusive_post_bg: "black", // hex color code does not work
    postCard: {},
    whiteColer: palette.d_white,
    priceSliderBg: palette.d_slider_bg,
    priceSliderPointBg: palette.d_slider_point,
    otherprofileInactiveTabColor: palette.d_otherprofile_inactiveTab,
    sectionBackground: palette.d_section_bg,
    perticularShoutoutSectionBg: palette.d_perticular_shoutout_sectionBg,
    gradientBgClr: "linear-gradient(96.81deg, #D33AFF 0%, #FF71A4 100%)",
    gradientActiveBtnClr: palette.l_btn_gradient_bg,
    leftIcon: {
      position: "absolute",
      top: "50%",
      left: "0",
      cursor: "pointer",
      transform: "translateY(-50%)",
    },
    rightIcon: {
      position: "absolute",
      top: "25px",
      right: "20px",
      cursor: "pointer",
      transform: "translateY(-50%)",
    },
    loginBg: {
    },
    signupBg: {
    },
    forgetPassBg: {
    },
    documentBg: {
    },
    button: {
      text: palette.d_app_text,
      background: palette.d_light_grey,
      fontFamily: `"Roboto", "sans-serif"`,
      fontSize: "15px",
      fontWeight: "normal",
      padding: "10px 15px",
      border: "none",
      margin: "10px 0",
    },
    blueButton: {
      text: palette.white,
      background: palette.d_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: "none",
    },
    bulkButton: {
      text: palette.white,
      background: palette.d_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "6px 15px",
      margin: "0",
      border: "none",
    },
    global__btn: {
      background: palette.white,
      color: palette.l_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: "none",
    },
    dv_blueButton: {
      background: palette.d_base,
      text: palette.white,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "1.171vw",
      fontWeight: "600",
      padding: "10px 6px",
      border: "none",
      margin: "0",
    },
    blueBorderButton: {
      text: palette.d_base,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.d_base}`,
    },
    redBorderButton: {
      text: palette.d_red,
      background: palette.transparent,
      hoverBackground: palette.d_red,
      hoverText: palette.white,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "5px 15px",
      margin: "0",
      border: `1px solid ${palette.d_red}`,
    },
    redButton: {
      text: palette.white,
      background: palette.d_red,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
    },
    dv_blueBorderButton: {
      text: palette.d_base,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "1.171vw",
      fontWeight: "600",
      padding: "10px 6px",
      margin: "0",
      border: `1px solid ${palette.d_base}`,
    },
    whiteButton: {
      text: palette.white,
      background: palette.d_app_bg,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0 auto",
      border: "none",
      position: "relative",
    },
    whiteBorderButton: {
      text: palette.black,
      background: palette.transparent,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.black}`,
    },
    greyBorderButton: {
      background: palette.transparent,
      text: palette.d_light_grey,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      border: `1px solid ${palette.d_light_grey}`,
    },
    header: {
      position: "sticky",
      left: "0",
      top: "0",
      zIndex: "101",
      width: "100%",
      background: palette.l_profileCard_bgColor,
      zIndex: 99,
    },
    inputBox: {
      padding: "0 0 0 15px",
      background: palette.d_section_bg,
      border: "none",
      borderRadius: "20px",
      height: "44px",
      fontSize: "16px",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.d_app_text,
    },
    search_input: {
      padding: "0 0 0 50px",
      background: palette.d_input_bg,
      border: `1px solid ${palette.d_input_bg}`,
      borderRadius: "20px",
      height: "44px",
      fontSize: "16px",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.d_app_text,
    },
    dv_search_input: {
      width: "18.594vw",
      padding: "0 0 0 2.562vw",
      background: palette.d_input_bg,
      border: "none",
      borderRadius: "1.611vw",
      height: "2.928vw",
      fontSize: "1.098vw",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.d_app_text,
    },
    dv_markatePlace_input: {
      width: "100%",
      padding: "0 0 0 2.562vw",
      background: palette.d_input_bg,
      border: "none",
      borderRadius: "1.611vw",
      height: "2.928vw",
      fontSize: "1.098vw",
      fontFamily: `"Roboto", sans-serif !important`,
      color: palette.d_app_text,
    },
    searchIcon: {
      position: "absolute",
      top: "50%",
      left: "20px",
      zIndex: "9",
      transform: "translateY(-50%)",
    },
    borderBtm: {
      borderBottom: `1px solid ${palette.d_border}`,
    },
    blueColorFieldButton: {
      text: palette.d_app_text,
      background: palette.d_base,
      fontFamily: `"Roboto", sans-serif !important`,
      fontSize: "15px",
      fontWeight: "600",
      padding: "10px 15px",
      margin: "0",
      border: `1px solid ${palette.d_base}`,
    },
  },
};

export default customTheme;
