export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME;
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH;
export const TIMELINE_PLACEHOLDER =
    BASE_PATH + "/images/mobile/svg/timeline_placeholder.svg";
export const BACK_TO_TOP = BASE_PATH + '/images/desktop/icons/back_to_top.svg';
export const BANNER_PLACEHOLDER_IMAGE = BASE_PATH + '/images/mobile/svg/bannerPlaceholderImage.svg';
export const IMAGE_LOCK_ICON = BASE_PATH + '/images/icons/lock-icon.svg';
export const IMAGE_LOCK_ICON2 = BASE_PATH + '/images/icons/lock-icon-2.svg';
export const FILM_ICON = BASE_PATH + '/images/icons/film.svg';
export const BANNER_PLACEHOLDER_IMAGE_COVER = BASE_PATH + '/images/dv-placeholder.svg';
export const isCameoTheme = process.env.NEXT_PUBLIC_ISCAMEO;

export const rightSideIcon = BASE_PATH + '/images/icons/rightSideIcon.svg';
export const leftSideIcon = BASE_PATH + '/images/icons/leftSideIcon.svg';
export const hashtag_icon = BASE_PATH + '/images/icons/hashtag_icon.svg';
export const Creator_Icon = BASE_PATH + '/images/mobile/svg/creator_icon.svg';
export const NAV_CHAT_ICON = BASE_PATH + '/images/profile_images/icons/chat_icon.svg';
export const INSIGHT = BASE_PATH + '/images/icons/insight.svg';
export const request_shotuout_post = BASE_PATH + '/images/shoutout_web/shoutout_post.svg';
export const LIKE_ICON = BASE_PATH + '/images/mobile/time line icons/Like.svg';
export const LIKE_POST_ICON = BASE_PATH + '/images/mobile/heart.svg';
export const UNLIKE_POST_ICON = BASE_PATH + '/images/mobile/Likeicon.svg';
export const COMMENT_ICON = BASE_PATH + '/images/mobile/time line icons/comment.svg';
export const SEND_POST_ICON = BASE_PATH + '/images/mobile/time line icons/sendicon.svg';
export const BOOKMARK_ICON = BASE_PATH + '/images/mobile/time line icons/Bookmark.svg';
export const FILL_BOOKMARK_ICON = BASE_PATH + '/images/mobile/time line icons/Bookmark-fill.svg';
export const DOLLAR_ICON = BASE_PATH + '/images/mobile/time line icons/Dollar_tip.svg';
export const more_symbol = BASE_PATH + '/images/otherUser_profile_assests/more_symbol.svg';
export const right_slick_arrow = BASE_PATH + "/images/icons/rightSlickArrow.svg";
export const left_slick_arrow = BASE_PATH + "/images/icons/leftSlickArrow.svg";
export const right_slick_arrow_dark = BASE_PATH + "/images/icons/rightSlickDarkArrow.svg";
export const left_slick_arrow_dark = BASE_PATH + "/images/icons/leftSlickDarkArrow.svg";
export const volume_mute = BASE_PATH + '/images/icons/volume_mute.svg';
export const volume_up = BASE_PATH + '/images/icons/volume_up.svg';
export const playIconStory = BASE_PATH + '/images/markate-place-page/playIcon.svg';
export const STAR_ICON_OTHERPROFIE = BASE_PATH + '/images/icons/starIcon.svg';
export const user_category_time = BASE_PATH + '/images/markate-place-page/time.svg';
export const tagIcon = BASE_PATH + '/images/markate-place-page/tagIcon.svg';
export const UNLOCK_ICON = BASE_PATH + '/images/mobile/svg/unlocked.svg';
export const DV_Sent_Tip = BASE_PATH + '/images/desktop/icons/sent_tip.svg';
export const leftSideIconWhite = BASE_PATH + '/images/icons/leftSideIconWhite.svg';
export const rightSideIconWhite = BASE_PATH + '/images/icons/rightSideIconWhite.svg';
export const backArrow = BASE_PATH + '/images/icons/back-arrow.svg';
export const IMOGI = BASE_PATH + '/images/chat/smily.svg';
export const Arrow_Left2 = BASE_PATH + '/images/icons/ArrowLeft2.svg'
export const COVER_IMAGE_ICON = BASE_PATH + '/images/icons/cover-image.svg'
export const LOGINBANNER = BASE_PATH + '/images/agency/loginbanner.png'
export const DEVICE = BASE_PATH + '/images/agency/Device.svg'
export const USER_AG = BASE_PATH + '/images/agency/user.svg'
export const RELOAD_AG = BASE_PATH + '/images/agency/reload.svg'
export const DELETE_AG = BASE_PATH + '/images/agency/delete.svg'
export const BLOCK_AG = BASE_PATH + '/images/agency/Block.svg'
export const BLOCKED = BASE_PATH + '/images/icons/Blocked.svg'
export const CAMERA_AG = BASE_PATH + '/images/agency/camera.svg'
export const FACEBOOK_AG = BASE_PATH + '/images/agency/facebook.png'
export const INSTARGAM_AG = BASE_PATH + '/images/agency/instagram.png'
export const TWITTER_AG = BASE_PATH + '/images/agency/twitter.png'
export const BANNER_AG = BASE_PATH + '/images/agency/Banner2.png'
export const UserMigrartionLoginBanner = BASE_PATH + '/images/userMigrartionLoginBanner.png'
export const UserMigrartionLoginBannerMobile = BASE_PATH + '/images/userMigrationBannerMobile.png'

export const VIDEO_IMAGE_PLACEHOLDER = BASE_PATH + '/images/video-placeholder.jpg'
