// guest authenticate actions
export const DEMO_ACTION_TYPE = "DEMO_ACTION_TYPE";
export const AUTH_INIT_GUEST_LOGIN = "AUTH_INIT_GUEST_LOGIN";
export const ACTIVATE_GUEST = "ACTIVATE_GUEST";
export const INIT_LANGUAGE_CHANGE = "INIT_LANGUAGE_CHANGE";
export const ACTIVE_PROFILE = "ACTIVE_PROFILE";
export const SERVER_LOGIN = "SERVER_LOGIN";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_GUEST_TOKEN = "SET_GUEST_TOKEN";
// Added By Bhavleen on June 10th, 2021
export const UPDATE_SUB_PLAN_PROFILE = "UPDATE_SUB_PLAN_PROFILE";
// Added By Bhavleen on April 19th, 2021
export const UPDATE_PROFILE_FOLLOWING = "UPDATE_PROFILE_FOLLOWING";
export const SET_PG = "SET_PG";
export const UPDATE_VIDEOCALL_PRICE = "UPDATE_VIDEOCALL_PRICE"

export const SUBMIT_PROFILE = "SUBMIT_PROFILE";

// Add Credit-Debit Card
export const GET_CARDS = "GET_CARDS";
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS";
export const DELETE_CARD = "DELETE_CARD";

// Add Address
export const GETADDRESS = "GETADDRESS";
export const GETADDRESS_SUCCESS = "GETADDRESS_SUCCESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

// Wallet
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLETS = "GET_WALLETS";
export const PURCHASE_SUCCESS_FROM_WALLET = "PURCHASE_SUCCESS_FROM_WALLET"

// Reacharge
export const RECHARGE_SUCCESS = "RECHARGE_SUCCESS"


// posting
export const POSTING = "POSTING";

// stories
export const SET_OWN_STORIES = "SET_OWN_STORIES";

//SEO
export const SET_SEO_SETTINGS = "SET_SEO_SETTINGS";

//Mobile View
export const IS_MOBILE = "IS_MOBILE";

export const IS_TABLET = "IS_TABLET";

export const SET_SUBSCRIPTION_PLAN = "SET_SUBSCRIPTION_PLAN";

export const UPDATE_POPULAR_POST = "UPDATE_POPULAR_POST";

export const UPDATE_LATEST_POST = "UPDATE_LATEST_POST";
export const SET_CLOUDINARY_CREDS = "SET_CLOUDINARY_CREDS";

// change theme
export const CHANGE_THEME = "CHANGE_THEME";
export const POST_SHOUTOUT_REQUEST_DATA = "POST_SHOUTOUT_REQUEST_DATA"

export const GET_NOTIFICATION_COUNT = "GET_NOTIFICATION_COUNT";

export const GET_CHAT_NOTIFICATION_COUNT = "GET_CHAT_NOTIFICATION_COUNT";

export const GET_BANNERS_IMGS = "GET_BANNERS_IMGS";
export const GET_RECENT_SEARCHES = "GET_RECENT_SEARCHES";

// SET APP CONFIG
export const SET_APP_CONFIG = "SET_APP_CONFIG";

// UPDATE SHOUTOUT ORDER COUNT
export const UPDATE_ORDER_COUNT = "UPDATE_ORDER_COUNT"

// homepage header categories
export const HEADER_CATEGORIES = "HEADER_CATEGORIES"

// Change CRM setting
export const CRM_CHANGE_SETTING = "CRM_CHANGE_SETTING";

export const GET_APP_UPDATE_BOT = "GET_APP_UPDATE_BOT";
export const MARK_UPDATES_STATUS = "MARK_UPDATES_STATUS";

export const UPDATE_VIEWED_HASHTAG = "UPDATE_VIEWED_HASHTAG";
export const UPDATE_HASHTAG = "UPDATE_HASHTAG";

// Change Theme Global
export const SET_COMMON_UTILITY = "SET_COMMON_UTILITY";

// Other Profile All Data
export const OTHER_ALL_DATA = "OTHER_ALL_DATA";

export const UPDATE_OTHER_PROFILE_DATA = "UPDATE_OTHER_PROFILE_DATA";

export const EMPTY_OTHER_PROFILE_DATA = "EMPTY_OTHER_PROFILE_DATA";

export const UPDATE_BOOKMARK_POSTSLIDER = "UPDATE_BOOKMARK_POSTSLIDER"

export const UPDATE_PURCHASED_POST = "UPDATE_PURCHASED_POST"
export const SEND_PURCHASED_EXCLUSIVE_DATA_TO_REDUX = "SEND_PURCHASED_EXCLUSIVE_DATA_TO_REDUX"
export const MY_AGENCY_DATA = "MY_AGENCY_DATA"
export const AGENCY_DATA = "AGENCY_DATA"


//handle comment count other profile

export const UPDATE_COMMENT_COUNT_OTHERPROFILE = "UPDATE_COMMENT_COUNT_OTHERPROFILE"

//handle video set extended stream
export const SET_SELECTED_SLOT_EXTENDED_STREAM = "SET_SELECTED_SLOT_EXTENDED_STREAM"

export const SETTOGGLE_SIDEBAR_DROPDOWN = "SETTOGGLE_SIDEBAR_DROPDOWN"

//handle suc=bscription cancel
export const SET_CANCEL_SUBSCRIPTION_ID = "SET_CANCEL_SUBSCRIPTION_ID"

export const CARDS_LIST = "CARDS_LIST";
export const UPDATE_CARDS_LIST = "UPDATE_CARDS_LIST";
//agecncy

export const AGENCY_PROFILE_DATA = "AGENCY_PROFILE_DATA"
export const AGENCY_OWNER_DATA = "AGENCY_OWNER_DATA"
export const AGENCY_CREATOR_REQUEST = "AGENCY_CREATOR_REQUEST"
export const SELECTED_EMPLOYEE = "SELECTED_EMPLOYEE"
export const CREATOR_AGENCY_DATA = "CREATOR_AGENCY_DATA"
export const EMPLOYEE_DATA = "EMPLOYEE_DATA"
export const ALL_EMPLOYEE_DATA = "ALL_EMPLOYEE_DATA"
export const SELECT_CREATOR = "SELECT_CREATOR"
export const UPADTE_CREATOR_AGENCY_DATA = "UPADTE_CREATOR_AGENCY_DATA"
export const UPDATE_EMPLOYEE_DATA = "UPDATE_EMPLOYEE_DATA"

